config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'interest_calculator#index'

  post 'calculate_total', to: 'interest_calculator#calculate', as:'calculate_total'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/interest_calculator_controller.rb
# frozen_string_literal: true

class InterestCalculatorController < ApplicationController
  def index
    @interest_paid_period = CalculatorConstants::INTEREST_PAID_PERIOD
  end

  def calculate
    @service_calculator = CalculateTermAmount.new(params)
    @service_calculator.call

    update_total_amount
  end

  private

  def update_total_amount
    render turbo_stream:
      turbo_stream.update('total-calculation',
        partial: 'interest_calculator/total_amount',
        locals: { service_calculator: @service_calculator })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interest_calculator_helper.rb
module InterestCalculatorHelper
end

app/views/interest_calculator/_total_amount.html.erb
<div>
    <% if service_calculator.successful? %>
        <p><b>Fixed Term Return</b> : <%=service_calculator.total_amount%></p>
    <% else %>
        <p><%=service_calculator.errors[:message]%></p>
    <% end %>
</div>

app/views/interest_calculator/index.html.erb
<h1>Interest Calculator</h1>
<div>
    <%= form_with url: calculate_total_path, method: :post do |form| %>
        <%= form.label :principle, "Start Deposit Amount:" %>
        <%= form.number_field :principle, min: 0, required: true %>
        </br>
        <%= form.label :interest_rate, "Interest Rate:" %>
        <%= form.number_field :interest_rate, step: "any", min: 0, required: true%>
        </br>
        <%= form.label :investment_term, "Investment Term:" %>
        <%= form.number_field :investment_term, min: 0, required: true %>
        </br>
        <%= form.label :interest_paid, "Interest Paid:" %>
        <%= form.collection_radio_buttons :interest_paid, @interest_paid_period, :last, :first, checked: @interest_paid_period.last %>
        </br>
        <%= form.submit "Calculate" %>
    <% end %>

    <%= turbo_frame_tag "total-calculation" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodeChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>